import {DEFAULT_LIFECYCLE_TRANSITIONS, type ModulaModuleManifest} from '@modula/module-standard'

const vaultNoteRecordSchema = {
  type: 'object',
  additionalProperties: false,
  required: ['id', 'title', 'body', 'createdAt', 'updatedAt'],
  properties: {
    id: {type: 'string'},
    title: {type: 'string', minLength: 1},
    body: {type: 'string'},
    tags: {type: 'array', items: {type: 'string'}},
    createdAt: {type: 'string', format: 'date-time'},
    updatedAt: {type: 'string', format: 'date-time'},
  },
}

const moduleId = 'digital.modula.vault-notes'
const publisher = {
  id: 'modula',
  name: 'Modula',
  website: 'https://modula.digital',
}

export const vaultNotesManifestFixture: ModulaModuleManifest = {
  schemaVersion: '1.0.0',
  standardVersion: '1.0.0',
  moduleVersion: '1.0.0',
  manifestSchemaVersion: '1.0.0',
  dataSchemaVersion: '1.0.0',
  id: moduleId,
  slug: 'vault-notes',
  name: 'Vault Notes',
  description: 'First-party reference manifest for private notes under Modula Module Standard 1.0.',
  publisher,
  compatibility: {
    host: '^1.0.0',
    runtime: '^1.0.0',
    standard: '^1.0.0',
    platforms: ['ios', 'android', 'web', 'server'],
  },
  lifecycle: {
    executionMode: 'declarative',
    defaultState: 'installed',
    allowedTransitions: DEFAULT_LIFECYCLE_TRANSITIONS,
    uninstall: {dataPolicy: 'retain', requiresConfirmation: true},
  },
  permissions: [
    {id: 'records:vault-notes:read', reason: 'Read private Vault Notes records for the owning account.', required: true, risk: 'low', policyMode: 'observe'},
    {id: 'records:vault-notes:write', reason: 'Create and update private Vault Notes records.', required: true, risk: 'medium', policyMode: 'warn'},
    {id: 'records:vault-notes:delete', reason: 'Delete private Vault Notes after explicit user intent.', required: true, risk: 'high', policyMode: 'require-confirmation'},
  ],
  capabilities: [
    {id: 'records', required: true, reason: 'Store note records.'},
    {id: 'views', required: true, reason: 'Render declarative module views.'},
    {id: 'functions', required: true, reason: 'Expose contract-only note functions.'},
    {id: 'events', required: true, reason: 'Emit note lifecycle events.'},
    {id: 'search', required: false, reason: 'Index searchable note metadata and selected content.', degradedBehavior: 'Notes remain browsable inside the module without universal search.'},
    {id: 'ai', required: false, reason: 'Allow host-mediated summaries for selected notes.', degradedBehavior: 'AI summaries and extraction controls are hidden.'},
    {id: 'automations', required: false, reason: 'Allow user-confirmed note automations.', degradedBehavior: 'Automation recipes are unavailable.'},
  ],
  records: [
    {
      id: `${moduleId}.record.note`,
      schema: vaultNoteRecordSchema,
      ownership: 'account',
      visibility: 'private',
      indexes: [{fields: ['updatedAt']}, {fields: ['title']}],
      uniqueness: {keys: ['id'], scope: 'account'},
      retention: {policy: 'retain'},
      aiPolicy: {allowed: true, context: 'record-content', policyMode: 'require-confirmation'},
      searchPolicy: {searchable: true, indexedFields: ['title', 'body', 'tags'], sensitiveFields: ['body'], visibility: 'private'},
      auditPolicy: {events: ['note.created', 'note.updated', 'note.deleted'], includeRecordBody: false},
      exportPolicy: {allowed: true, formats: ['json', 'markdown']},
    },
  ],
  views: [
    {id: `${moduleId}.view.collection`, type: 'collection', title: 'Vault Notes', recordId: `${moduleId}.record.note`, permissions: ['records:vault-notes:read'], layout: {kind: 'list', primaryField: 'title'}},
    {id: `${moduleId}.view.detail`, type: 'detail', title: 'Vault Note', recordId: `${moduleId}.record.note`, permissions: ['records:vault-notes:read'], layout: {kind: 'detail', fields: ['title', 'body', 'tags']}},
    {id: `${moduleId}.view.form`, type: 'form', title: 'Edit Vault Note', recordId: `${moduleId}.record.note`, permissions: ['records:vault-notes:write'], layout: {kind: 'form', fields: ['title', 'body', 'tags']}},
    {id: `${moduleId}.view.settings`, type: 'settings', title: 'Vault Notes Settings', permissions: [], layout: {kind: 'settings'}},
    {id: `${moduleId}.view.empty`, type: 'empty-state', title: 'No Notes', permissions: [], layout: {kind: 'empty'}},
    {id: `${moduleId}.view.error`, type: 'error-state', title: 'Vault Notes Error', permissions: [], layout: {kind: 'error'}},
    {id: `${moduleId}.view.loading`, type: 'loading-state', title: 'Loading Vault Notes', permissions: [], layout: {kind: 'loading'}},
  ],
  actions: [
    {
      id: `${moduleId}.action.create-note`,
      title: 'Create Vault Note',
      functionId: `${moduleId}.function.create-note`,
      permissions: ['records:vault-notes:write'],
      confirmationPolicy: {required: false, policyMode: 'observe'},
      sideEffects: ['record.create'],
      audit: {event: 'note.create-requested', includeInput: false},
    },
  ],
  functions: [
    {
      id: `${moduleId}.function.create-note`,
      title: 'Create Vault Note',
      inputSchema: vaultNoteRecordSchema,
      outputSchema: {type: 'object', required: ['id'], properties: {id: {type: 'string'}}},
      permissions: ['records:vault-notes:write'],
      aiCallable: false,
      automationCallable: true,
      idempotent: true,
      sideEffects: ['record.create'],
      timeoutMs: 10000,
      rateLimit: {windowSeconds: 60, maxCalls: 60},
      audit: {event: 'note.created', includeInput: false, includeOutput: false},
      confirmationPolicy: {required: false, risk: 'medium'},
    },
    {
      id: `${moduleId}.function.summarize-note`,
      title: 'Summarize Vault Note',
      inputSchema: {type: 'object', required: ['noteId'], properties: {noteId: {type: 'string'}}},
      outputSchema: {type: 'object', required: ['summary'], properties: {summary: {type: 'string'}}},
      permissions: ['records:vault-notes:read'],
      aiCallable: true,
      automationCallable: false,
      idempotent: true,
      sideEffects: [],
      timeoutMs: 30000,
      rateLimit: {windowSeconds: 60, maxCalls: 20},
      audit: {event: 'note.ai-summary-requested', includeInput: false, includeOutput: false},
      confirmationPolicy: {required: true, risk: 'medium'},
    },
  ],
  settings: [
    {
      id: `${moduleId}.settings.main`,
      scope: 'installation',
      schema: {type: 'object', properties: {showRecentOnBoard: {type: 'boolean'}, aiSummariesEnabled: {type: 'boolean'}}},
      defaults: {showRecentOnBoard: true, aiSummariesEnabled: false},
    },
  ],
  events: [
    {id: `${moduleId}.event.note-created`, type: 'note.created', direction: 'emitted', schemaVersion: '1.0.0', schema: {type: 'object', required: ['noteId'], properties: {noteId: {type: 'string'}}}, permissions: [], replaySupport: true},
    {id: `${moduleId}.event.note-updated`, type: 'note.updated', direction: 'emitted', schemaVersion: '1.0.0', schema: {type: 'object', required: ['noteId'], properties: {noteId: {type: 'string'}}}, permissions: [], replaySupport: true},
    {id: `${moduleId}.event.profile-updated`, type: 'profile.updated', direction: 'consumed', schemaVersion: '1.0.0', schema: {type: 'object'}, subscriber: `${moduleId}.subscriber.profile-updated`, permissions: [], replaySupport: false},
  ],
  automations: [
    {
      id: `${moduleId}.automation.create-note-from-selection`,
      title: 'Create Note From Selection',
      triggers: [{kind: 'user-selected-text'}],
      conditions: [],
      actions: [`${moduleId}.action.create-note`],
      recipes: [{id: 'selection-to-note'}],
      executionPolicy: {policyMode: 'require-confirmation', maxRuntimeMs: 30000},
      confirmationPolicy: {required: true, reason: 'Creating a note stores user-selected content.'},
    },
  ],
  search: [
    {
      id: `${moduleId}.search.notes`,
      recordId: `${moduleId}.record.note`,
      indexedFields: ['title', 'body', 'tags'],
      rankingHints: {titleBoost: 3, recencyBoost: 2},
      sensitiveFields: ['body'],
      visibility: 'private',
      projectionHandler: {kind: 'declarative', projection: {title: 'title', body: 'body', tags: 'tags'}},
    },
  ],
  ai: [
    {
      id: `${moduleId}.ai.summaries`,
      features: ['summarize', 'extract'],
      allowedContext: ['record-content', 'user-selected-text'],
      toolDefinitions: [{id: `${moduleId}.function.summarize-note`, mode: 'host-ai-request-contract'}],
      structuredOutputs: [{type: 'object', required: ['summary'], properties: {summary: {type: 'string'}}}],
      permissions: ['records:vault-notes:read'],
      policyMode: 'require-confirmation',
    },
  ],
  diagnostics: {
    components: ['startup', 'runtime', 'permissions', 'dependencies', 'search', 'ai', 'connector', 'health'],
    warnings: [],
    errors: [],
    startup: {checks: ['manifest']},
    runtime: {executionMode: 'declarative'},
    permissions: {required: ['records:vault-notes:read', 'records:vault-notes:write']},
    dependencies: {external: []},
    search: {definitions: [`${moduleId}.search.notes`]},
    ai: {gatewayOnly: true},
    connector: {required: false},
    health: {status: 'healthy'},
  },
  health: {
    status: 'healthy',
    components: [
      {id: 'manifest', status: 'healthy'},
      {id: 'records', status: 'healthy'},
      {id: 'search', status: 'degraded', message: 'Optional until host search capability is granted.'},
      {id: 'ai', status: 'degraded', message: 'Optional until host AI capability is granted.'},
    ],
    checkDefinitions: [
      {id: 'manifest-validate', component: 'startup', timeoutMs: 1000, required: true},
      {id: 'records-contract', component: 'runtime', timeoutMs: 1000, required: true},
      {id: 'search-projection', component: 'search', timeoutMs: 1000, required: false},
      {id: 'ai-gateway-contract', component: 'ai', timeoutMs: 1000, required: false},
    ],
  },
  migrations: {
    dataSchemaVersion: '1.0.0',
    steps: [
      {id: `${moduleId}.migration.1-0-0`, from: '0.0.0', to: '1.0.0', reversible: true, checksum: '9'.repeat(64)},
    ],
  },
  release: {
    repository: 'modula-mod/modula-module-vault-notes',
    commitSha: '0123456789abcdef0123456789abcdef01234567',
    checksum: 'a'.repeat(64),
    licenseEvidence: ['LICENSE', 'README.md'],
    signing: {signed: false},
    channel: 'stable',
    reviewStatus: 'approved',
    securityAdvisories: [],
  },
  trust: {
    publisher,
    level: 'first-party',
    provenance: {sourceVerified: true, checksumVerified: true, signatureVerified: false},
    review: {status: 'approved', evidence: ['first-party-source-review']},
    security: {advisories: []},
  },
}

export const standardHostCapabilities = [
  'records',
  'views',
  'actions',
  'functions',
  'events',
  'automations',
  'ai',
  'search',
  'settings',
  'diagnostics',
  'health',
  'migrations',
] as const
