import {DEFAULT_LIFECYCLE_TRANSITIONS, createDefaultModuleSectionVersions, type ModulaModuleManifest} from '@modula/module-standard'

const vaultNoteRecordSchema = {
  type: 'object',
  additionalProperties: false,
  required: ['id', 'title', 'body', 'createdAt', 'updatedAt'],
  properties: {
    id: {type: 'string'},
    title: {type: 'string', minLength: 1},
    body: {type: 'string'},
    tags: {type: 'array', items: {type: 'string'}},
    createdAt: {type: 'string', format: 'date-time'},
    updatedAt: {type: 'string', format: 'date-time'},
  },
}

const moduleId = 'digital.modula.vault-notes'
const publisher = {
  id: 'modula',
  name: 'Modula',
  website: 'https://modula.digital',
}

export const vaultNotesManifestFixture: ModulaModuleManifest = {
  schemaVersion: '1.0.0',
  standardVersion: '1.0.0',
  moduleVersion: '1.0.0',
  manifestSchemaVersion: '1.0.0',
  dataSchemaVersion: '1.0.0',
  id: moduleId,
  slug: 'vault-notes',
  name: 'Vault Notes',
  description: 'First-party reference manifest for private notes under Modula Module Standard 1.0.',
  publisher,
  compatibility: {
    host: '^1.0.0',
    runtime: '^1.0.0',
    standard: '^1.0.0',
    platforms: ['ios', 'android', 'web', 'server'],
  },
  lifecycle: {
    executionMode: 'declarative',
    defaultState: 'installed',
    allowedTransitions: DEFAULT_LIFECYCLE_TRANSITIONS,
    uninstall: {dataPolicy: 'retain', requiresConfirmation: true},
  },
  permissions: [
    {id: 'records:vault-notes:read', reason: 'Read private Vault Notes records for the owning account.', required: true, risk: 'low', policyMode: 'observe'},
    {id: 'records:vault-notes:write', reason: 'Create and update private Vault Notes records.', required: true, risk: 'medium', policyMode: 'warn'},
    {id: 'records:vault-notes:delete', reason: 'Delete private Vault Notes after explicit user intent.', required: true, risk: 'high', policyMode: 'require-confirmation'},
  ],
  capabilities: [
    {id: 'records', required: true, reason: 'Store note records.'},
    {id: 'views', required: true, reason: 'Render declarative module views.'},
    {id: 'functions', required: true, reason: 'Expose contract-only note functions.'},
    {id: 'events', required: true, reason: 'Emit note lifecycle events.'},
    {id: 'search', required: false, reason: 'Index searchable note metadata and selected content.', degradedBehavior: 'Notes remain browsable inside the module without universal search.'},
    {id: 'ai', required: false, reason: 'Allow host-mediated summaries for selected notes.', degradedBehavior: 'AI summaries and extraction controls are hidden.'},
    {id: 'automations', required: false, reason: 'Allow user-confirmed note automations.', degradedBehavior: 'Automation recipes are unavailable.'},
  ],
  records: [
    {
      id: `${moduleId}.record.note`,
      schema: vaultNoteRecordSchema,
      ownership: 'account',
      visibility: 'private',
      indexes: [{fields: ['updatedAt']}, {fields: ['title']}],
      uniqueness: {keys: ['id'], scope: 'account'},
      retention: {policy: 'retain'},
      aiPolicy: {allowed: true, context: 'record-content', policyMode: 'require-confirmation'},
      searchPolicy: {searchable: true, indexedFields: ['title', 'body', 'tags'], sensitiveFields: ['body'], visibility: 'private'},
      auditPolicy: {events: ['note.created', 'note.updated', 'note.deleted'], includeRecordBody: false},
      exportPolicy: {allowed: true, formats: ['json', 'markdown']},
    },
  ],
  views: [
    {id: `${moduleId}.view.collection`, type: 'collection', title: 'Vault Notes', recordId: `${moduleId}.record.note`, permissions: ['records:vault-notes:read'], layout: {kind: 'list', primaryField: 'title'}},
    {id: `${moduleId}.view.detail`, type: 'detail', title: 'Vault Note', recordId: `${moduleId}.record.note`, permissions: ['records:vault-notes:read'], layout: {kind: 'detail', fields: ['title', 'body', 'tags']}},
    {id: `${moduleId}.view.form`, type: 'form', title: 'Edit Vault Note', recordId: `${moduleId}.record.note`, permissions: ['records:vault-notes:write'], layout: {kind: 'form', fields: ['title', 'body', 'tags']}},
    {id: `${moduleId}.view.settings`, type: 'settings', title: 'Vault Notes Settings', permissions: [], layout: {kind: 'settings'}},
    {id: `${moduleId}.view.empty`, type: 'empty-state', title: 'No Notes', permissions: [], layout: {kind: 'empty'}},
    {id: `${moduleId}.view.error`, type: 'error-state', title: 'Vault Notes Error', permissions: [], layout: {kind: 'error'}},
    {id: `${moduleId}.view.loading`, type: 'loading-state', title: 'Loading Vault Notes', permissions: [], layout: {kind: 'loading'}},
  ],
  actions: [
    {
      id: `${moduleId}.action.create-note`,
      title: 'Create Vault Note',
      functionId: `${moduleId}.function.create-note`,
      permissions: ['records:vault-notes:write'],
      confirmationPolicy: {required: false, policyMode: 'observe'},
      sideEffects: ['record.create'],
      audit: {event: 'note.create-requested', includeInput: false},
    },
  ],
  functions: [
    {
      id: `${moduleId}.function.create-note`,
      title: 'Create Vault Note',
      inputSchema: vaultNoteRecordSchema,
      outputSchema: {type: 'object', required: ['id'], properties: {id: {type: 'string'}}},
      permissions: ['records:vault-notes:write'],
      aiCallable: false,
      automationCallable: true,
      idempotent: true,
      sideEffects: ['record.create'],
      timeoutMs: 10000,
      rateLimit: {windowSeconds: 60, maxCalls: 60},
      audit: {event: 'note.created', includeInput: false, includeOutput: false},
      confirmationPolicy: {required: false, risk: 'medium'},
    },
    {
      id: `${moduleId}.function.summarize-note`,
      title: 'Summarize Vault Note',
      inputSchema: {type: 'object', required: ['noteId'], properties: {noteId: {type: 'string'}}},
      outputSchema: {type: 'object', required: ['summary'], properties: {summary: {type: 'string'}}},
      permissions: ['records:vault-notes:read'],
      aiCallable: true,
      automationCallable: false,
      idempotent: true,
      sideEffects: [],
      timeoutMs: 30000,
      rateLimit: {windowSeconds: 60, maxCalls: 20},
      audit: {event: 'note.ai-summary-requested', includeInput: false, includeOutput: false},
      confirmationPolicy: {required: true, risk: 'medium'},
    },
  ],
  settings: [
    {
      id: `${moduleId}.settings.main`,
      scope: 'installation',
      schema: {type: 'object', properties: {showRecentOnBoard: {type: 'boolean'}, aiSummariesEnabled: {type: 'boolean'}}},
      defaults: {showRecentOnBoard: true, aiSummariesEnabled: false},
    },
  ],
  events: [
    {id: `${moduleId}.event.note-created`, type: 'note.created', direction: 'emitted', schemaVersion: '1.0.0', schema: {type: 'object', required: ['noteId'], properties: {noteId: {type: 'string'}}}, permissions: [], replaySupport: true},
    {id: `${moduleId}.event.note-updated`, type: 'note.updated', direction: 'emitted', schemaVersion: '1.0.0', schema: {type: 'object', required: ['noteId'], properties: {noteId: {type: 'string'}}}, permissions: [], replaySupport: true},
    {id: `${moduleId}.event.profile-updated`, type: 'profile.updated', direction: 'consumed', schemaVersion: '1.0.0', schema: {type: 'object'}, subscriber: `${moduleId}.subscriber.profile-updated`, permissions: [], replaySupport: false},
  ],
  automations: [
    {
      id: `${moduleId}.automation.create-note-from-selection`,
      title: 'Create Note From Selection',
      triggers: [{kind: 'user-selected-text'}],
      conditions: [],
      actions: [`${moduleId}.action.create-note`],
      recipes: [{id: 'selection-to-note'}],
      executionPolicy: {policyMode: 'require-confirmation', maxRuntimeMs: 30000},
      confirmationPolicy: {required: true, reason: 'Creating a note stores user-selected content.'},
    },
  ],
  search: [
    {
      id: `${moduleId}.search.notes`,
      recordId: `${moduleId}.record.note`,
      indexedFields: ['title', 'body', 'tags'],
      rankingHints: {titleBoost: 3, recencyBoost: 2},
      sensitiveFields: ['body'],
      visibility: 'private',
      projectionHandler: {kind: 'declarative', projection: {title: 'title', body: 'body', tags: 'tags'}},
    },
  ],
  ai: [
    {
      id: `${moduleId}.ai.summaries`,
      features: ['summarize', 'extract'],
      allowedContext: ['record-content', 'user-selected-text'],
      toolDefinitions: [{id: `${moduleId}.function.summarize-note`, mode: 'host-ai-request-contract'}],
      structuredOutputs: [{type: 'object', required: ['summary'], properties: {summary: {type: 'string'}}}],
      permissions: ['records:vault-notes:read'],
      policyMode: 'require-confirmation',
    },
  ],
  diagnostics: {
    components: ['startup', 'runtime', 'permissions', 'dependencies', 'search', 'ai', 'connector', 'health'],
    warnings: [],
    errors: [],
    startup: {checks: ['manifest']},
    runtime: {executionMode: 'declarative'},
    permissions: {required: ['records:vault-notes:read', 'records:vault-notes:write']},
    dependencies: {external: []},
    search: {definitions: [`${moduleId}.search.notes`]},
    ai: {gatewayOnly: true},
    connector: {required: false},
    health: {status: 'healthy'},
  },
  health: {
    status: 'healthy',
    components: [
      {id: 'manifest', status: 'healthy'},
      {id: 'records', status: 'healthy'},
      {id: 'search', status: 'degraded', message: 'Optional until host search capability is granted.'},
      {id: 'ai', status: 'degraded', message: 'Optional until host AI capability is granted.'},
    ],
    checkDefinitions: [
      {id: 'manifest-validate', component: 'startup', timeoutMs: 1000, required: true},
      {id: 'records-contract', component: 'runtime', timeoutMs: 1000, required: true},
      {id: 'search-projection', component: 'search', timeoutMs: 1000, required: false},
      {id: 'ai-gateway-contract', component: 'ai', timeoutMs: 1000, required: false},
    ],
  },
  migrations: {
    dataSchemaVersion: '1.0.0',
    steps: [
      {id: `${moduleId}.migration.1-0-0`, from: '0.0.0', to: '1.0.0', reversible: true, checksum: '9'.repeat(64)},
    ],
  },
  release: {
    repository: 'modula-mod/modula-module-vault-notes',
    commitSha: '0123456789abcdef0123456789abcdef01234567',
    checksum: 'a'.repeat(64),
    licenseEvidence: ['LICENSE', 'README.md'],
    signing: {signed: false},
    channel: 'stable',
    reviewStatus: 'approved',
    securityAdvisories: [],
  },
  trust: {
    publisher,
    level: 'first-party',
    provenance: {sourceVerified: true, checksumVerified: true, signatureVerified: false},
    review: {status: 'approved', evidence: ['first-party-source-review']},
    security: {advisories: []},
  },
}

export const standardHostCapabilities = [
  'records',
  'views',
  'actions',
  'functions',
  'events',
  'automations',
  'ai',
  'search',
  'settings',
  'diagnostics',
  'health',
  'migrations',
] as const

export const vaultNotesStandard20ManifestFixture = {
  ...vaultNotesManifestFixture,
  schemaVersion: '2.0.0',
  standardVersion: '2.0.0',
  manifestSchemaVersion: '2.0.0',
  moduleVersion: '2.0.0',
  description: 'First-party reference manifest for private notes under Modula Module Standard 2.0.',
  compatibility: {
    ...vaultNotesManifestFixture.compatibility,
    standard: '^2.0.0',
    platforms: ['ios', 'android', 'web', 'server', 'desktop'],
  },
  capabilities: [
    ...vaultNotesManifestFixture.capabilities,
    {id: 'services', required: false, reason: 'Publish Vault Notes services for other modules.', degradedBehavior: 'Other modules call records and APIs directly through Greenfield.'},
    {id: 'apis', required: false, reason: 'Expose note APIs under the Greenfield module API registry.', degradedBehavior: 'Other modules use action contracts only.'},
    {id: 'hooks', required: false, reason: 'Publish lifecycle and record hooks.', degradedBehavior: 'No hooks are subscribed.'},
    {id: 'jobs', required: false, reason: 'Declare host-managed reindex and cleanup jobs.', degradedBehavior: 'Maintenance is manual.'},
    {id: 'widgets', required: false, reason: 'Expose profile and Board widgets.', degradedBehavior: 'Vault Notes remains route-only.'},
    {id: 'storage', required: false, reason: 'Describe record, history, attachment and index storage.', degradedBehavior: 'Storage diagnostics are reduced.'},
    {id: 'offline', required: false, reason: 'Prepare sync contracts for mobile.', degradedBehavior: 'Online-only behavior.'},
    {id: 'realtime', required: false, reason: 'Publish change events for subscribers.', degradedBehavior: 'Subscribers poll the API.'},
  ],
  health: {
    ...vaultNotesManifestFixture.health,
    components: [
      ...vaultNotesManifestFixture.health.components,
      {id: 'api-registry', status: 'healthy'},
      {id: 'service-registry', status: 'healthy'},
    ],
  },
  sectionVersions: createDefaultModuleSectionVersions(),
  identity: {version: '2.0.0', metadata: {moduleId, publisherId: publisher.id, profileScoped: true}},
  dependencyGraph: {
    version: '2.0.0',
    requires: [],
    optional: [{provides: 'digital.modula.notifications', versionRange: '^1.0.0', reason: 'Notify users about shared or pinned notes.'}],
    recommended: [{provides: 'digital.modula.search', versionRange: '^1.0.0', reason: 'Improve universal search ranking.'}],
    conflicts: [{moduleId: 'digital.modula.legacy-vault-notes', versionRange: '*', reason: 'Legacy note storage is replaced by Standard 2.0 records.'}],
    replaces: [],
    provides: [
      {id: `${moduleId}.provides.customer-record-attachments`, title: 'Note attachments for CRM and Tasks', version: '1.0.0', kind: 'api'},
      {id: `${moduleId}.provides.private-note-records`, title: 'Private note records', version: '1.0.0', kind: 'record'},
    ],
  },
  serviceRegistry: {
    version: '2.0.0',
    items: [
      {id: `${moduleId}.service.search`, title: 'Search Service', version: '1.0.0', kind: 'search', contract: `${moduleId}.contract.search`, permissions: ['records:vault-notes:read'], capabilities: ['search']},
      {id: `${moduleId}.service.export`, title: 'Export Service', version: '1.0.0', kind: 'export', contract: `${moduleId}.contract.export`, permissions: ['records:vault-notes:read'], capabilities: ['exports']},
      {id: `${moduleId}.service.autosave`, title: 'Autosave Service', version: '1.0.0', kind: 'autosave', contract: `${moduleId}.contract.autosave`, permissions: ['records:vault-notes:write'], capabilities: ['records']},
      {id: `${moduleId}.service.revision`, title: 'Revision Service', version: '1.0.0', kind: 'revision', contract: `${moduleId}.contract.revision`, permissions: ['records:vault-notes:read'], capabilities: ['history']},
      {id: `${moduleId}.service.history`, title: 'History Service', version: '1.0.0', kind: 'history', contract: `${moduleId}.contract.history`, permissions: ['records:vault-notes:read'], capabilities: ['history']},
      {id: `${moduleId}.service.markdown`, title: 'Markdown Service', version: '1.0.0', kind: 'markdown', contract: `${moduleId}.contract.markdown`, permissions: ['records:vault-notes:read'], capabilities: ['exports']},
    ],
  },
  apiRegistry: {
    version: '2.0.0',
    items: [
      {id: `${moduleId}.api.create-note`, title: 'Create Note', version: '1.0.0', method: 'POST', path: `/api/modula/${moduleId}/notes`, inputSchema: 'schemas/note.schema.json', outputSchema: 'schemas/note.schema.json', permissions: ['records:vault-notes:write'], sideEffects: 'write', idempotent: true},
      {id: `${moduleId}.api.update-note`, title: 'Update Note', version: '1.0.0', method: 'PATCH', path: `/api/modula/${moduleId}/notes/{noteId}`, inputSchema: 'schemas/note.schema.json', outputSchema: 'schemas/note.schema.json', permissions: ['records:vault-notes:write'], sideEffects: 'write', idempotent: true},
      {id: `${moduleId}.api.archive-note`, title: 'Archive Note', version: '1.0.0', method: 'POST', path: `/api/modula/${moduleId}/notes/{noteId}/archive`, outputSchema: 'schemas/note.schema.json', permissions: ['records:vault-notes:write'], sideEffects: 'write', idempotent: true},
      {id: `${moduleId}.api.export-note`, title: 'Export Note', version: '1.0.0', method: 'POST', path: `/api/modula/${moduleId}/exports`, outputSchema: 'schemas/export.schema.json', permissions: ['records:vault-notes:read'], sideEffects: 'read', idempotent: true},
      {id: `${moduleId}.api.search`, title: 'Search Notes', version: '1.0.0', method: 'GET', path: `/api/modula/${moduleId}/search`, outputSchema: 'schemas/search.schema.json', permissions: ['records:vault-notes:read'], sideEffects: 'read', idempotent: true},
      {id: `${moduleId}.api.history`, title: 'Note History', version: '1.0.0', method: 'GET', path: `/api/modula/${moduleId}/notes/{noteId}/history`, outputSchema: 'schemas/history.schema.json', permissions: ['records:vault-notes:read'], sideEffects: 'read', idempotent: true},
      {id: `${moduleId}.api.attachments`, title: 'Attachments', version: '1.0.0', method: 'POST', path: `/api/modula/${moduleId}/notes/{noteId}/attachments`, outputSchema: 'schemas/attachment.schema.json', permissions: ['records:vault-notes:write'], sideEffects: 'write', idempotent: true},
    ],
  },
  eventBus: {version: '2.0.0', items: ['created', 'updated', 'deleted', 'opened', 'viewed', 'shared', 'archived', 'pinned', 'unpinned', 'exported', 'imported', 'health-changed', 'settings-changed', 'ai-completed'].map(event => ({id: `${moduleId}.event-contract.${event}`, title: event, version: '1.0.0'}))},
  hookRegistry: {
    version: '2.0.0',
    items: ['BeforeCreateRecord', 'AfterCreateRecord', 'BeforeDelete', 'BeforeExport', 'AfterExport', 'BeforeInstall', 'AfterInstall', 'BeforeEnable', 'AfterEnable', 'BeforeDisable', 'AfterDisable', 'BeforeUninstall', 'AfterUninstall'].map(hook => ({
      id: `${moduleId}.hook.${hook.replace(/[A-Z]/g, match => `-${match.toLowerCase()}`).replace(/^-/, '')}`,
      hook,
      phase: hook.startsWith('After') ? 'after' : 'before',
      target: moduleId,
      policyMode: 'observe',
    })),
  },
  capabilityDiscovery: {version: '2.0.0', supportsSearch: true, supportsExport: true, supportsAI: true, supportsOffline: true, supportsRealtime: true, supportsNotifications: true, supportsWidgets: true, supportsAutomation: true, supportsSync: true, supportsHistory: true, supportsSharing: true, supportsEncryption: true, supportsMedia: true, supportsComments: false, supportsPresence: false, supportsVoice: false, supportsVideo: false, supportsBackend: true, supportsCustomBackend: false, supportsSelfHosted: true},
  healthModel: {version: '2.0.0', items: [{id: `${moduleId}.health.overall`, status: 'healthy'}, {id: `${moduleId}.health.search`, status: 'search-rebuilding'}]},
  diagnosticsModel: {version: '2.0.0', items: ['logs', 'statistics', 'performance', 'storage', 'database', 'cache', 'queues', 'ai', 'search', 'exports', 'imports', 'jobs', 'backend', 'network', 'permissions', 'health'].map(name => ({id: `${moduleId}.diagnostics.${name}`, title: name}))},
  metrics: {version: '2.0.0', items: ['install-count', 'open-count', 'usage', 'storage', 'searches', 'exports', 'ai-calls', 'errors', 'latency', 'average-execution', 'memory', 'cpu', 'bandwidth', 'background-jobs', 'sync'].map(name => ({id: `${moduleId}.metric.${name}`, title: name, version: '1.0.0'}))},
  permissionModel: {
    version: '2.0.0',
    categories: {
      data: [{id: 'records:vault-notes:read', reason: 'Read private notes.', required: true, risk: 'low', policyMode: 'observe'}],
      ai: [{id: 'ai.request', reason: 'Request host-mediated AI note actions.', required: false, risk: 'medium', policyMode: 'require-confirmation'}],
      search: [{id: 'search:index', reason: 'Index private note projections.', required: false, risk: 'medium', policyMode: 'warn'}],
      background: [{id: 'jobs:create', reason: 'Run cleanup and reindex jobs.', required: false, risk: 'high', policyMode: 'require-confirmation'}],
    },
  },
  jobRegistry: {version: '2.0.0', items: [{id: `${moduleId}.job.reindex`, title: 'Reindex notes', kind: 'reindex', functionId: `${moduleId}.function.create-note`}, {id: `${moduleId}.job.cleanup`, title: 'Cleanup note tombstones', kind: 'cleanup'}]},
  storageModel: {version: '2.0.0', items: [{id: `${moduleId}.storage.records`, kind: 'structured-records', version: '1.0.0', encrypted: true, retention: 'retain'}, {id: `${moduleId}.storage.attachments`, kind: 'attachments', version: '1.0.0', encrypted: true, retention: 'retain'}, {id: `${moduleId}.storage.history`, kind: 'history', version: '1.0.0', encrypted: true, retention: 'bounded'}]},
  widgetRegistry: {version: '2.0.0', items: [{id: `${moduleId}.widget.board`, title: 'Recent Notes', surface: 'board', viewId: `${moduleId}.view.collection`, permissions: ['records:vault-notes:read']}, {id: `${moduleId}.widget.profile`, title: 'Profile Notes', surface: 'profile', viewId: `${moduleId}.view.collection`, permissions: ['records:vault-notes:read']}]},
  navigationRegistry: {version: '2.0.0', items: [{id: `${moduleId}.navigation.route`, title: 'Vault Notes', kind: 'route', target: `/module/${moduleId}`, surface: 'module'}, {id: `${moduleId}.navigation.quick-action`, title: 'New note', kind: 'quick-action', target: `${moduleId}.action.create-note`, surface: 'board'}]},
  uiContributions: {version: '2.0.0', items: [{id: `${moduleId}.ui.board-card`, title: 'Vault Notes card', kind: 'board-card', target: 'board', contract: `${moduleId}.contract.board-card`}, {id: `${moduleId}.ui.profile-tab`, title: 'Vault Notes tab', kind: 'profile-tab', target: 'profile', contract: `${moduleId}.contract.profile-tab`}]},
  automationRegistry: {version: '2.0.0', items: [{id: `${moduleId}.automation.selection-to-note`, title: 'Selection to note', triggers: ['user.selectedText'], actions: [`${moduleId}.action.create-note`], conditions: []}]},
  offline: {version: '2.0.0', capable: true, syncStrategy: 'background', conflictStrategy: 'manual-review', compression: true, encryption: true},
  realtime: {version: '2.0.0', events: ['note.created', 'note.updated', 'note.deleted', 'note.archived'], presence: false, typing: false, watchers: true, subscriptions: [`${moduleId}.records.note`], channels: [`module:${moduleId}`]},
  versioning: {version: '2.0.0', moduleVersion: '2.0.0', standardVersion: '2.0.0', protocolVersion: '1.0.0', backendVersion: '1.0.0', schemaVersion: '1.0.0', manifestVersion: '2.0.0', aiVersion: '1.0.0', migrationVersion: '1.0.0', searchVersion: '1.0.0', runtimeVersion: '1.0.0'},
  compatibilityMatrix: {version: '2.0.0', modulaVersion: '^1.0.0', greenfieldVersion: '^1.0.0', moduleStandardVersion: '^2.0.0', runtimeVersion: '^1.0.0', backendRuntime: '^1.0.0', connectorRuntime: '^1.0.0', aiRuntime: '^1.0.0', engineRuntime: '^1.0.0', platforms: ['ios', 'android', 'web', 'desktop', 'server']},
  marketplace: {version: '2.0.0', publisherVerification: 'first-party', publisherProfile: 'https://modula.digital', verifiedBadge: true, license: 'LicenseRef-Modula-First-Party', source: 'github', repository: 'modula-mod/modula-module-vault-notes', ciStatus: 'passing', securityScore: 100, downloads: 0, changelog: 'CHANGELOG.md', roadmap: 'README.md', support: 'https://modula.digital/support', documentation: 'README.md', issueTracker: 'https://github.com/modula-mod/modula-module-vault-notes/issues', pricing: 'included', requiredRuntimes: ['greenfield'], aiSupport: true, backendMode: 'greenfield-managed'},
  engineReadiness: {version: '2.0.0', engines: ['declarative-ui', 'records', 'actions', 'functions', 'ai', 'automation', 'documents']},
  exports: {version: '2.0.0', items: [{id: `${moduleId}.export.markdown`, title: 'Markdown export'}]},
  imports: {version: '2.0.0', items: [{id: `${moduleId}.import.markdown`, title: 'Markdown import'}]},
  synchronization: {version: '2.0.0', items: [{id: `${moduleId}.sync.notes`, title: 'Notes sync'}]},
  integrations: {version: '2.0.0', items: []},
  billing: {version: '2.0.0', items: []},
  telemetry: {version: '2.0.0', items: []},
  accessibility: {version: '2.0.0', items: []},
  localization: {version: '2.0.0', items: []},
  appearance: {version: '2.0.0', items: []},
  onboarding: {version: '2.0.0', items: []},
} satisfies ModulaModuleManifest & Record<string, unknown>

export const vaultNotesStandard21ManifestFixture = {
  ...vaultNotesStandard20ManifestFixture,
  schemaVersion: '2.1.0',
  standardVersion: '2.1.0',
  manifestSchemaVersion: '2.1.0',
  description: 'First-party reference module manifest exposing governed extension points under Modula Module Standard 2.1.',
  compatibility: {...vaultNotesStandard20ManifestFixture.compatibility, standard: '^2.1.0'},
  sectionVersions: createDefaultModuleSectionVersions('2.1.0'),
  versioning: {...vaultNotesStandard20ManifestFixture.versioning, version: '2.1.0', standardVersion: '2.1.0', manifestVersion: '2.1.0'},
  compatibilityMatrix: {...vaultNotesStandard20ManifestFixture.compatibilityMatrix, version: '2.1.0', moduleStandardVersion: '^2.1.0'},
  extensionProduct: {
    version: '1.0.0',
    kind: 'module',
    targets: [],
    extensionPoints: [
      {id: `${moduleId}.home.section`, title: 'Vault Notes home section', contributionKinds: ['home.section'], maxContributions: 20},
      {id: `${moduleId}.editor.toolbar`, title: 'Vault Notes editor toolbar', contributionKinds: ['toolbar.action'], requiredCapability: 'notes.editor.contribute', maxContributions: 20},
      {id: `${moduleId}.editor.command`, title: 'Vault Notes editor commands', contributionKinds: ['editor.command'], requiredCapability: 'notes.editor.contribute', maxContributions: 40},
      {id: `${moduleId}.editor.attachment`, title: 'Vault Notes editor attachments', contributionKinds: ['editor.attachment'], requiredCapability: 'notes.attachments.create', maxContributions: 20},
      {id: `${moduleId}.note.actions`, title: 'Vault Notes note actions', contributionKinds: ['menu.item', 'contextMenu.item'], requiredCapability: 'notes.actions.contribute', maxContributions: 40},
      {id: `${moduleId}.note.inspector`, title: 'Vault Notes note inspector', contributionKinds: ['view.section', 'record.decorator'], maxContributions: 20},
      {id: `${moduleId}.search.provider`, title: 'Vault Notes search providers', contributionKinds: ['search.provider'], requiredCapability: 'notes.search', maxContributions: 10},
      {id: `${moduleId}.composer.tool`, title: 'Vault Notes composer tools', contributionKinds: ['composer.tool'], maxContributions: 20},
      {id: `${moduleId}.settings.section`, title: 'Vault Notes settings sections', contributionKinds: ['settings.section'], maxContributions: 20},
      {id: `${moduleId}.note.after-save`, title: 'Vault Notes after-save actions', contributionKinds: ['background.action'], requiredCapability: 'notes.events.subscribe', maxContributions: 20},
    ],
    contributions: [],
    retention: {defaultMode: 'KEEP_DATA', supportsUserChoice: true, metadataNamespace: moduleId},
    graphPolicy: {maxDepth: 8, maxNodes: 128},
  },
} satisfies ModulaModuleManifest & Record<string, unknown>

const formattingId = 'digital.modula.vault-notes.formatting'

export const vaultFormattingStandard21ManifestFixture = {
  ...vaultNotesStandard21ManifestFixture,
  id: formattingId,
  slug: 'vault-notes-formatting',
  name: 'Vault Formatting Tools',
  description: 'Reference frontend-only plugin contributing declarative formatting commands to Vault Notes.',
  moduleVersion: '0.1.0',
  compatibility: {...vaultNotesStandard21ManifestFixture.compatibility, standard: '^2.1.0'},
  lifecycle: {...vaultNotesStandard21ManifestFixture.lifecycle, uninstall: {dataPolicy: 'purge', requiresConfirmation: true}},
  permissions: [
    {id: 'notes.read', reason: 'Read the current note only when the user invokes a formatting command.', required: true, risk: 'low', policyMode: 'observe'},
    {id: 'notes.editor.contribute', reason: 'Register declared formatting commands in the Vault Notes editor.', required: true, risk: 'low', policyMode: 'observe'},
  ],
  capabilities: [
    {id: 'functions', required: true, reason: 'Expose deterministic formatting functions.'},
    {id: 'ui-contributions', required: true, reason: 'Contribute declarative editor commands.'},
  ],
  records: [],
  views: [],
  actions: [],
  functions: [
    {
      id: `${formattingId}.function.copy-markdown`,
      title: 'Copy as Markdown',
      inputSchema: {type: 'object', required: ['noteId'], properties: {noteId: {type: 'string'}}},
      outputSchema: {type: 'object', required: ['markdown'], properties: {markdown: {type: 'string'}}},
      permissions: ['notes.read'],
      aiCallable: false,
      automationCallable: false,
      idempotent: true,
      sideEffects: [],
      timeoutMs: 5000,
      rateLimit: {windowSeconds: 60, maxCalls: 120},
      audit: {event: 'extension.action.invoked', includeInput: false, includeOutput: false},
      confirmationPolicy: {required: false, risk: 'low'},
    },
  ],
  settings: [],
  events: [],
  automations: [],
  search: [],
  ai: [],
  migrations: {dataSchemaVersion: '1.0.0', steps: []},
  release: {...vaultNotesStandard21ManifestFixture.release, repository: 'modula-mod/modula-vault-notes-formatting'},
  trust: {...vaultNotesStandard21ManifestFixture.trust, publisher},
  backend: {mode: 'frontend-only'},
  identity: {version: '2.1.0', metadata: {moduleId: formattingId, publisherId: publisher.id}},
  dependencyGraph: {
    version: '2.1.0',
    requires: [{moduleId, versionRange: '>=1.1.0 <2.0.0', reason: 'Formatting commands extend the Vault Notes editor.', capabilityIds: ['notes.read', 'notes.editor.contribute']}],
    optional: [],
    recommended: [],
    conflicts: [],
    replaces: [],
    provides: [{id: `${formattingId}.provides.editor-commands`, title: 'Vault Notes formatting commands', version: '1.0.0', kind: 'ui'}],
  },
  serviceRegistry: {version: '2.1.0', items: []},
  apiRegistry: {version: '2.1.0', items: []},
  eventBus: {version: '2.1.0', items: []},
  hookRegistry: {version: '2.1.0', items: []},
  capabilityDiscovery: {version: '2.1.0', supportsBackend: false, supportsWidgets: false},
  healthModel: {version: '2.1.0', items: [{id: `${formattingId}.health.overall`, status: 'healthy'}]},
  diagnosticsModel: {version: '2.1.0', items: []},
  metrics: {version: '2.1.0', items: []},
  permissionModel: {version: '2.1.0', categories: {data: [{id: 'notes.read', reason: 'Read the explicitly selected note.', required: true, risk: 'low', policyMode: 'observe'}]}},
  jobRegistry: {version: '2.1.0', items: []},
  storageModel: {version: '2.1.0', items: []},
  widgetRegistry: {version: '2.1.0', items: []},
  navigationRegistry: {version: '2.1.0', items: []},
  uiContributions: {version: '2.1.0', items: []},
  automationRegistry: {version: '2.1.0', items: []},
  offline: {version: '2.1.0', capable: true, syncStrategy: 'none'},
  realtime: {version: '2.1.0', events: []},
  versioning: {version: '2.1.0', moduleVersion: '0.1.0', standardVersion: '2.1.0', manifestVersion: '2.1.0'},
  compatibilityMatrix: {version: '2.1.0', moduleStandardVersion: '^2.1.0', runtimeVersion: '^1.0.0', platforms: ['ios', 'android', 'web', 'desktop']},
  marketplace: {...vaultNotesStandard21ManifestFixture.marketplace, version: '2.1.0', repository: 'modula-mod/modula-vault-notes-formatting', backendMode: 'frontend-only', aiSupport: false},
  engineReadiness: {version: '2.1.0', engines: ['declarative-ui', 'functions']},
  exports: {version: '2.1.0', items: []},
  imports: {version: '2.1.0', items: []},
  synchronization: {version: '2.1.0', items: []},
  integrations: {version: '2.1.0', items: []},
  billing: {version: '2.1.0', items: []},
  telemetry: {version: '2.1.0', items: []},
  accessibility: {version: '2.1.0', items: []},
  localization: {version: '2.1.0', items: []},
  appearance: {version: '2.1.0', items: []},
  onboarding: {version: '2.1.0', items: []},
  extensionProduct: {
    version: '1.0.0',
    kind: 'plugin',
    targets: [{productId: moduleId, versionRange: '>=1.1.0 <2.0.0', requiredCapabilities: ['notes.read', 'notes.editor.contribute'], requiredExtensionPoints: [`${moduleId}.editor.command`]}],
    extensionPoints: [],
    contributions: [
      {
        id: `${formattingId}.contribution.copy-markdown`,
        title: 'Copy as Markdown',
        kind: 'editor.command',
        extensionPoint: `${moduleId}.editor.command`,
        functionId: `${formattingId}.function.copy-markdown`,
        requiredCapability: 'notes.read',
        availability: {platforms: ['ios', 'android', 'web', 'desktop'], requiresOnline: false, requiredCapabilities: ['notes.editor.contribute']},
        priority: 100,
      },
    ],
    retention: {defaultMode: 'DELETE_DATA', supportsUserChoice: false, metadataNamespace: formattingId},
    graphPolicy: {maxDepth: 8, maxNodes: 128},
  },
} satisfies ModulaModuleManifest & Record<string, unknown>
